name: Lint (Hadolint)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
