name: Publish automatically on tag

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Check the the version of the tag matches the version specified in the version file
      - name: Check the version
        id: get_version
        run: |
          set -e
          TAG_VERSION="$(echo $GITHUB_REF | cut -d / -f 3)"
          FILE_VERSION="$(cat version)"
          [[ $TAG_VERSION == $FILE_VERSION ]]
          echo ::set-output name=VERSION::$FILE_VERSION

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # Get the tag and use that as the Traefik version
          build-args: TRAEFIK_VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/traefik:${{ steps.get_version.outputs.VERSION }},${{ secrets.DOCKER_HUB_USERNAME }}/traefik:latest 
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/traefik:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/traefik:buildcache,mode=max
