name: Lint & Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Get the version from the source code
      - name: Get the version
        id: get_version
        run: |
          FILE_VERSION="$(cat version)"
          echo ::set-output name=VERSION::$FILE_VERSION

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          # Do not publish the image!
          push: false
          # Get the tag and use that as the Traefik version
          build-args: TRAEFIK_VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/traefik:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/traefik:buildcache
